// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ethpandaops/lab-backend/internal/bounds (interfaces: Provider)
//
// Generated by this command:
//
//	mockgen -package mocks -destination mocks/mock_provider.go github.com/ethpandaops/lab-backend/internal/bounds Provider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	bounds "github.com/ethpandaops/lab-backend/internal/bounds"
	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GetAllBounds mocks base method.
func (m *MockProvider) GetAllBounds(ctx context.Context) map[string]*bounds.BoundsData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllBounds", ctx)
	ret0, _ := ret[0].(map[string]*bounds.BoundsData)
	return ret0
}

// GetAllBounds indicates an expected call of GetAllBounds.
func (mr *MockProviderMockRecorder) GetAllBounds(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllBounds", reflect.TypeOf((*MockProvider)(nil).GetAllBounds), ctx)
}

// GetBounds mocks base method.
func (m *MockProvider) GetBounds(ctx context.Context, network string) (*bounds.BoundsData, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBounds", ctx, network)
	ret0, _ := ret[0].(*bounds.BoundsData)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetBounds indicates an expected call of GetBounds.
func (mr *MockProviderMockRecorder) GetBounds(ctx, network any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBounds", reflect.TypeOf((*MockProvider)(nil).GetBounds), ctx, network)
}

// NotifyChannel mocks base method.
func (m *MockProvider) NotifyChannel() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyChannel")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// NotifyChannel indicates an expected call of NotifyChannel.
func (mr *MockProviderMockRecorder) NotifyChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyChannel", reflect.TypeOf((*MockProvider)(nil).NotifyChannel))
}

// Start mocks base method.
func (m *MockProvider) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockProviderMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockProvider)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockProvider) Stop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockProviderMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockProvider)(nil).Stop))
}
